### ISSUE TITLE
Migrate to Sheets v4 API

### ISSUE THREAD

**Issue by bharatkashyap** [bharatkashyap/quizgen-final#9]
Google Sheets has deprecated the v3 API ([info](https://developers.google.com/sheets/api/guides/migration)). As a result, the app has stopped working!

Need to migrate this to v4 API.

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by bharatkashyap** [comment]
Closed via ee831357bee39058d63be84e37ff17a1fb29e518
